// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrate needs a session-capable Postgres connection. Poolers (PgBouncer, Neon
    // pooler, Supabase 6543) often break `pg_advisory_lock`. Prefer an unpooled URL
    // here; the app still uses `DATABASE_URL` in `src/lib/prisma.ts`.
    url:
      process.env["DATABASE_URL_UNPOOLED"] ??
      process.env["DIRECT_URL"] ??
      process.env["DATABASE_URL"],
  },
});
