/**
 * Controlled vocabulary for SCRI `eventType` (docs/SCRI blueprint event families).
 * Ingest must use these codes; UI maps to short labels.
 */
export const SCR_EVENT_TYPES = [
  "PORT_CONGESTION",
  "TERMINAL_CLOSURE",
  "VESSEL_BACKLOG",
  "RAIL_DISRUPTION",
  "TRUCKING_RESTRICTION",
  "AIRPORT_DISRUPTION",
  "CANAL_TRANSIT",
  "ROUTE_SUSPENSION",
  "TYPHOON",
  "FLOOD",
  "EARTHQUAKE",
  "WILDFIRE",
  "DROUGHT_WATERWAY",
  "WINTER_STORM",
  "SANCTIONS",
  "TARIFF_CHANGE",
  "WAR_ESCALATION",
  "BORDER_DELAY",
  "CUSTOMS_RESTRICTION",
  "TRADE_COMPLIANCE_CHANGE",
  "STRIKE",
  "PROTEST",
  "LABOR_SHORTAGE",
  "UNION_ACTION",
  "CIVIL_UNREST",
  "FACTORY_SHUTDOWN",
  "BANKRUPTCY",
  "CAPACITY_LOSS",
  "OPERATIONAL_INCIDENT",
  "CONTAMINATION_RECALL",
  "POWER_SHORTAGE",
  "QUARANTINE",
  "EPIDEMIC_CONTROLS",
  "REGULATORY_INSPECTION",
  "DOCUMENTATION_RULE_CHANGE",
  "OTHER_SUPPLY_CHAIN_RISK",
] as const;

export type ScriEventTypeCode = (typeof SCR_EVENT_TYPES)[number];

const LABELS: Record<ScriEventTypeCode, string> = {
  PORT_CONGESTION: "Port congestion",
  TERMINAL_CLOSURE: "Terminal closure",
  VESSEL_BACKLOG: "Vessel backlog",
  RAIL_DISRUPTION: "Rail disruption",
  TRUCKING_RESTRICTION: "Trucking restriction",
  AIRPORT_DISRUPTION: "Airport disruption",
  CANAL_TRANSIT: "Canal / waterway transit",
  ROUTE_SUSPENSION: "Route suspension",
  TYPHOON: "Typhoon / cyclone",
  FLOOD: "Flood",
  EARTHQUAKE: "Earthquake",
  WILDFIRE: "Wildfire",
  DROUGHT_WATERWAY: "Drought (waterway)",
  WINTER_STORM: "Severe winter storm",
  SANCTIONS: "Sanctions",
  TARIFF_CHANGE: "Tariff / duty change",
  WAR_ESCALATION: "War / escalation",
  BORDER_DELAY: "Border delay",
  CUSTOMS_RESTRICTION: "Customs restriction",
  TRADE_COMPLIANCE_CHANGE: "Trade compliance change",
  STRIKE: "Strike",
  PROTEST: "Protest / unrest",
  LABOR_SHORTAGE: "Labor shortage",
  UNION_ACTION: "Union action",
  CIVIL_UNREST: "Civil unrest",
  FACTORY_SHUTDOWN: "Factory shutdown",
  BANKRUPTCY: "Bankruptcy / insolvency",
  CAPACITY_LOSS: "Capacity loss",
  OPERATIONAL_INCIDENT: "Operational incident",
  CONTAMINATION_RECALL: "Contamination / recall",
  POWER_SHORTAGE: "Power shortage",
  QUARANTINE: "Quarantine / controls",
  EPIDEMIC_CONTROLS: "Epidemic controls",
  REGULATORY_INSPECTION: "Regulatory inspection",
  DOCUMENTATION_RULE_CHANGE: "Documentation rules",
  OTHER_SUPPLY_CHAIN_RISK: "Other supply-chain risk",
};

export function scriEventTypeLabel(code: string): string {
  return LABELS[code as ScriEventTypeCode] ?? code.replace(/_/g, " ");
}
