/** Stable keys stored in `audit_results.discrepancyCategories` (JSON string array). */
export const DISCREPANCY_CATEGORY = {
  AMOUNT_MATCH_WITHIN_TOLERANCE: "AMOUNT_MATCH_WITHIN_TOLERANCE",
  AMOUNT_MINOR_DISCREPANCY: "AMOUNT_MINOR_DISCREPANCY",
  AMOUNT_MAJOR_DISCREPANCY: "AMOUNT_MAJOR_DISCREPANCY",
  NO_SNAPSHOT_LINE_MATCH: "NO_SNAPSHOT_LINE_MATCH",
  CURRENCY_MISMATCH: "CURRENCY_MISMATCH",
  AMBIGUOUS_SNAPSHOT_MATCH: "AMBIGUOUS_SNAPSHOT_MATCH",
  SNAPSHOT_PARSE_ERROR: "SNAPSHOT_PARSE_ERROR",
} as const;

export type DiscrepancyCategoryKey = (typeof DISCREPANCY_CATEGORY)[keyof typeof DISCREPANCY_CATEGORY];
